litrevu/litrevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('review.urls', namespace='review')),
    # path('', include('ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/review/urls.py
from django.urls import path

from .views import (
    FeedsView,
    CreateTicketView,
    CreateReviewView,
    CreateReviewForTicketView,
    PostsView,
    PostsModifyReviewView,
    PostDeleteReviewView,
    PostsModifyTicketView,
    PostDeleteTicketView,
)

app_name = "review"

urlpatterns = [
    path("feeds/", FeedsView.as_view(), name="feeds_page"),
    path("create-ticket/", CreateTicketView.as_view(), name="create_ticket"),
    path("create-review/", CreateReviewView.as_view(), name="create_review"),
    path(
        "create-review-ticket/<int:pk>/",
        CreateReviewForTicketView.as_view(),
        name="create_review_ticket",
    ),
    path("posts/", PostsView.as_view(), name="posts_page"),
    path(
        "posts/modify-review/<int:pk>",
        PostsModifyReviewView.as_view(),
        name="modify_review",
    ),
    path(
        "posts/delete-review/<int:pk>/",
        PostDeleteReviewView.as_view(),
        name="delete_review",
    ),
    path(
        "posts/modify-ticket/<int:pk>",
        PostsModifyTicketView.as_view(),
        name="modify_ticket",
    ),
    path(
        "posts/delete-ticket/<int:pk>/",
        PostDeleteTicketView.as_view(),
        name="delete_ticket",
    ),
]

litrevu/ui/urls.py
from django.urls import path

litrevu/review/models.py
from PIL import Image
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class Ticket(models.Model):
    """A ticket is related to a Review."""

    class Meta:
        verbose_name = _("ticket")
        verbose_name_plural = _("tickets")
        ordering = ["-time_created"]

    title = models.CharField(max_length=128, verbose_name=_("title of ticket"))
    description = models.TextField(
        max_length=2048, verbose_name=_("description"), blank=True
    )
    creator = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="ticket_creator",
        verbose_name=_("creator of ticket"),
    )
    image = models.ImageField(
        upload_to="images/", verbose_name=_("image"), blank=True, null=True
    )
    time_created = models.DateTimeField(
        auto_now_add=True, verbose_name=_("ticket created at")
    )

    def __str__(self):
        return f"{self.title} | {self.creator}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)
            img.thumbnail((250, 375))
            img.save(self.image.path)


class Review(models.Model):
    """A Review has a rating and a ticket."""

    # ONE_STAR = 1
    # TWO_STARS = 2
    # THREE_STARS = 3
    # FOUR_STARS = 4
    # FIVE_STARS = 5
    #
    # STARS_CHOICES = [
    #     (ONE_STAR, "1 star"),
    #     (TWO_STARS, "2 stars"),
    #     (THREE_STARS, "3 stars"),
    #     (FOUR_STARS, "4 stars"),
    #     (FIVE_STARS, "5 stars"),
    # ]

    class Meta:
        verbose_name = _("review")
        verbose_name_plural = _("reviews")
        ordering = ["-time_created"]

    ticket = models.ForeignKey(
        "review.Ticket",
        on_delete=models.CASCADE,
        related_name="reviews",
        verbose_name=_("ticket"),
    )
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name=_("rating"),
    )
    # rating = models.CharField(max_length=1, choices=STARS_CHOICES)
    headline = models.CharField(max_length=128, verbose_name=_("title of review"))
    body = models.TextField(verbose_name=_("comment"), blank=True)
    author = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="review_author",
        verbose_name=_("author"),
    )
    time_created = models.DateTimeField(
        auto_now_add=True, verbose_name=_("review created at")
    )

    def __str__(self):
        return str(self.headline)

litrevu/review/forms.py
from django import forms

from .models import Review, Ticket


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["headline", "rating", "body", "ticket"]

    rating = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=[
            (1, "1 star"),
            (2, "2 stars"),
            (3, "3 stars"),
            (4, "4 stars"),
            (5, "5 stars"),
        ],
    )


class ModifiedReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["headline", "rating", "body"]

    rating = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=[
            (1, "1 star"),
            (2, "2 stars"),
            (3, "3 stars"),
            (4, "4 stars"),
            (5, "5 stars"),
        ],
    )

litrevu/review/views.py
from itertools import chain

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import CharField, Q, Value
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy

from .forms import ReviewForm, ModifiedReviewForm
from .models import Ticket, Review


class FeedsView(LoginRequiredMixin, TemplateView):
    """All reviews and tickets on the feeds page"""

    template_name = "feeds/feeds_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tickets = (
            Ticket.objects.filter(reviews__isnull=True)
            .filter(
                Q(creator__followed_by__user=self.request.user)
                | Q(creator=self.request.user)
            )
            .distinct()
            .annotate(type_of_content=Value("TICKET", CharField()))
        )
        reviews = (
            Review.objects.filter(
                Q(author__followed_by__user=self.request.user)
                | Q(author=self.request.user)
                | Q(ticket__creator=self.request.user)
            )
            .distinct()
            .annotate(type_of_content=Value("REVIEW", CharField()))
        )
        context["posts"] = sorted(
            chain(reviews, tickets), key=lambda post: post.time_created, reverse=True
        )

        return context


class CreateTicketView(LoginRequiredMixin, CreateView):
    """Button: 'Ask for a review' View. Create a new ticket"""

    model = Ticket
    fields = ["title", "description", "image"]
    template_name = "feeds/create_ticket_page.html"
    success_url = reverse_lazy("review:feeds_page")

    def form_valid(self, form):
        ticket = form.save(commit=False)
        ticket.creator = self.request.user
        form.save()

        return super().form_valid(form)


class CreateReviewView(LoginRequiredMixin, CreateView):
    """Button: 'Create a review' on the top of the feeds or posts page.
    You choose a ticket to review."""

    # TODO: limit the queryset to the tickets of followed users

    model = Review
    form_class = ReviewForm
    template_name = "feeds/create_review_page.html"
    success_url = reverse_lazy("review:feeds_page")

    def form_valid(self, form):
        review = form.save(commit=False)
        review.author = self.request.user
        form.save()

        return super().form_valid(form)


class CreateReviewForTicketView(LoginRequiredMixin, CreateView):
    """Button 'Create a review' on a ticket without a review."""

    model = Review
    form_class = ModifiedReviewForm
    template_name = "feeds/create_review_for_ticket.html"
    success_url = reverse_lazy("review:feeds_page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ticket"] = Ticket.objects.get(pk=self.kwargs.get("pk"))

        return context

    def form_valid(self, form):
        review = form.save(commit=False)
        review.author = self.request.user
        review.ticket_id = self.kwargs["pk"]
        form.save()

        return super().form_valid(form)


class PostsView(LoginRequiredMixin, TemplateView):
    """All reviews and tickets on the feeds page"""

    template_name = "posts/posts_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tickets"] = Ticket.objects.filter(creator=self.request.user)
        context["reviews"] = Review.objects.filter(author=self.request.user)
        return context


class PostsModifyReviewView(LoginRequiredMixin, UpdateView):
    """View to modify a review"""

    model = Review
    form_class = ReviewForm
    template_name = "posts/posts_modify_review_page.html"
    success_url = reverse_lazy("review:posts_page")


class PostDeleteReviewView(LoginRequiredMixin, DeleteView):
    """DeleteView to remove a Review"""

    model = Review
    template_name = "posts/delete_confirmation.html"
    success_url = reverse_lazy("review:posts_page")


class PostsModifyTicketView(LoginRequiredMixin, UpdateView):
    """View to modify a ticket"""

    model = Ticket
    fields = ["title", "description", "image"]
    template_name = "posts/posts_modify_ticket_page.html"
    success_url = reverse_lazy("review:posts_page")


class PostDeleteTicketView(LoginRequiredMixin, DeleteView):
    """DeleteView to remove a Review"""

    model = Ticket
    template_name = "posts/delete_confirmation.html"
    success_url = reverse_lazy("review:posts_page")

litrevu/review/templates/posts/delete_confirmation.html
{% extends 'base_layout.html' %}
{% load static crispy_forms_tags %}

{% block content %}
<!--  delete confirmation  -->
<div class="container main">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card border-dark my-3" style="background-color: #e3f2fd;">
        <div class="card-body bg-transparent ">
          <h4 class="card-subtitle text-center py-2"> Confirmation: </h4>
          <form method="post">
          {% csrf_token %}
            <p> Are you sure you want to delete this ?</p>
            <div style="display: flex; justify-content: space-between;">
              <button type="submit" class="btn btn-primary margin-btn"> Yes </button>
              <a href="{% url 'review:posts_page' %}" role="button" class="btn btn-secondary margin-btn"> Cancel </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!--  end delete confirmation  -->
{% endblock %}

litrevu/review/templates/posts/posts_modify_review_page.html
{% extends 'base_layout.html' %}
{% load static crispy_forms_tags %}

{% block content %}
<!-- modify review/ticket page -->
<div class="container main">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card border-dark my-3" style="background-color: #e3f2fd;">
        <div class="card-body bg-transparent ">
          <h4 class="card-subtitle text-center py-2"> Modify a review: </h4>
          <form method="post">
          {% csrf_token %}
            {{ form|crispy }}
            <div style="display: flex; justify-content: space-between;">
              <button type="submit" class="btn btn-primary margin-btn"> Save </button>
              <a href="{% url 'review:posts_page' %}" role="button" class="btn btn-secondary margin-btn"> Cancel </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End of modify review/ticket page -->
{% endblock %}

litrevu/review/templates/posts/posts_modify_ticket_page.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- modify ticket page -->
<div class="container main">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card border-dark my-3" style="background-color: #e3f2fd;">
        <div class="card-body bg-transparent ">
          <h4 class="card-subtitle text-center py-2"> Modify a ticket: </h4>
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {{ form|crispy }}
            <div style="display: flex; justify-content: space-between;">
              <button type="submit" class="btn btn-primary margin-btn"> Save </button>
              <a href="{% url 'review:posts_page' %}" role="button" class="btn btn-secondary margin-btn"> Cancel </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End of modify ticket page -->
{% endblock %}

litrevu/review/templates/posts/posts_page.html
{% extends 'base_layout.html' %}
{% load static stars %}

{% block content %}
<!-- posts page -->
<div class="container main">
  <div style="display: flex;">
    <div style="width: -moz-available;">
      <h3 style="padding-left: 20px;"> {{ request.user }}'s Posts </h3>
    </div>
    <div class="headline-feed">
      <a class="btn btn-primary m-1" href="{% url 'review:create_ticket' %}" role="button"> Ask for a review </a>
      <a class="btn btn-primary m-1" href="{% url 'review:create_review' %}" role="button"> Create a review </a>
    </div>
  </div>

  <hr>
  <div class="container justify-content-center">
    <form method="post">
    {% csrf_token %}
      {% for review in reviews %}
        <div class="container mt-3">
          <div class="card border-dark my-3 w-80" style="background-color: #e3f2fd;">
            <div class="card-body">
              <p> posted by <strong>{{ review.author }}</strong> <small style="float: right;"> {{ review.time_created }} </small> </p>
              <hr>
              <h4> {{ review.headline }} </h4>
              <p>{{ review.rating|display_stars }}</p>
              <p> {{ review.body|linebreaks }} </p>
              <div class="card border-dark bg-light">
                <div class="card-body">
                  <p> posted by <strong>{{ review.ticket.creator }}</strong> <small style="float: right;"> {{ review.ticket.time_created }} </small> </p>
                  <hr>
                  <div style="display: flex;">
                    <img src="{% get_media_prefix %}{{ review.ticket.image }}" alt="{{ review.ticket.title }}" class="img-fluid img-border">
                    <div style="margin-left: 30px;">
                      <div style="margin-bottom: 15px;">
                        <h4> {{ review.ticket.title }} </h4>
                      </div>
                      <div>
                        <p> {{ review.ticket.description|linebreaks }} </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                <a class="btn btn-primary" href="{% url 'review:modify_review' pk=review.id %}" role="button" style="margin-top: 20px;"> Modify </a>
                <a class="btn btn-danger" href="{% url 'review:delete_review' pk=review.id %}" role="button" style="margin-top: 20px;"> Delete </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </form>

    {% if reviews %}
      <br>
      <hr>
      <br>
    {% endif %}

    <form method="post">
    {% csrf_token %}
      {% for ticket in tickets %}
        <div class="container mt-3">
          <div class="card border-dark my-3 w-80" style="background-color: #e3f2fd;">
            <div class="card-body">
              <p> posted by <strong>{{ ticket.creator }}</strong> <small style="float: right;"> {{ ticket.time_created }} </small> </p>
              <hr>
              <div style="display: flex;">
                <img src="{% get_media_prefix %}{{ ticket.image }}" alt="{{ ticket.title }}" class="img-fluid img-border" >
                <div style="margin-left: 30px;">
                  <div style="margin-bottom: 15px;">
                    <h4> {{ ticket.title }} </h4>
                  </div>
                  <div>
                    <p class="card-text"> {{ ticket.description|linebreaks }} </p>
                  </div>
                </div>
              </div>
                <a class="btn btn-primary" href="{% url 'review:modify_ticket' pk=ticket.id %}" role="button" style="margin-top: 20px;"> Modify </a>
                <a class="btn btn-danger" href="{% url 'review:delete_ticket' pk=ticket.id %}" role="button" style="margin-top: 20px;"> Delete </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </form>
  </div>
</div>
<!-- End of posts page -->
{% endblock %}