litrevu/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView, AboFollowView, AboUnfollowView

app_name = "accounts"

urlpatterns = [
    path("", LoginView.as_view(template_name="login_page.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("abo/", AboFollowView.as_view(), name="abo_page"),
    path("abo-unfollow/<int:pk>/", AboUnfollowView.as_view(), name="abo_unfollow"),
]

litrevu/litrevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('review.urls', namespace='review')),
    # path('', include('ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/review/urls.py
from django.urls import path

from .views import (
    FeedsView,
    CreateTicketView,
    CreateReviewView,
    CreateReviewForTicketView,
    PostsView,
    PostsModifyReviewView,
    PostDeleteReviewView,
    PostsModifyTicketView,
    PostDeleteTicketView,
)

app_name = "review"

urlpatterns = [
    path("feeds/", FeedsView.as_view(), name="feeds_page"),
    path("create-ticket/", CreateTicketView.as_view(), name="create_ticket"),
    path("create-review/", CreateReviewView.as_view(), name="create_review"),
    path(
        "create-review-ticket/<int:pk>/",
        CreateReviewForTicketView.as_view(),
        name="create_review_ticket",
    ),
    path("posts/", PostsView.as_view(), name="posts_page"),
    path(
        "posts/modify-review/<int:pk>",
        PostsModifyReviewView.as_view(),
        name="modify_review",
    ),
    path(
        "posts/delete-review/<int:pk>/",
        PostDeleteReviewView.as_view(),
        name="delete_review",
    ),
    path(
        "posts/modify-ticket/<int:pk>",
        PostsModifyTicketView.as_view(),
        name="modify_ticket",
    ),
    path(
        "posts/delete-ticket/<int:pk>/",
        PostDeleteTicketView.as_view(),
        name="delete_ticket",
    ),
]

litrevu/ui/urls.py
from django.urls import path

litrevu/ui/models.py
from django.db import models

# Create your models here.

litrevu/ui/views.py
from django.shortcuts import render

litrevu/ui/templates/base_layout.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>LITRevu - CBV</title>

        <!-- bootstrap cdn -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

        <!-- font-awesome cdn -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- custom css files -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/crispy-forms.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

    </head>
    <body>
      <!-- Navbar -->
      <nav class="navbar fixed-top navbar-expand-lg" style="background-color: #e3f2fd; border-bottom: solid grey 1px;">
      <!-- Navbar content -->
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'review:feeds_page' %}">LITReview</a>
          {% if user.is_authenticated %}
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'review:feeds_page' %}"> Feeds </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'review:posts_page' %}"> Posts </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:abo_page' %}"> Abo </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}"> Log out </a>
                  </li>
                </ul>
              </div>
          {% endif %}
        </div>
      </nav>
      <!-- End of Navbar -->

      <!-- Alert/Messages -->
      {% include 'messages.html' %}
      <!-- End of Alert/Messages -->

      {% block content %}

      {% endblock %}

      <!-- bootstrap script -->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    </body>
    </html>

litrevu/ui/templates/messages.html
<div class="mt-4" style="width: 98%; padding-top: 40px;">
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <div class="container-fluid p-0">
          <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }}
          </div>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
</div>