litrevu/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView, AboFollowView, AboUnfollowView

app_name = "accounts"

urlpatterns = [
    path("", LoginView.as_view(template_name="login_page.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("abo/", AboFollowView.as_view(), name="abo_page"),
    path("abo-unfollow/<int:pk>/", AboUnfollowView.as_view(), name="abo_unfollow"),
]

litrevu/litrevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('review.urls', namespace='review')),
    # path('', include('ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/ui/urls.py
from django.urls import path

litrevu/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """create User instance"""

    pass


class UserFollow(models.Model):
    """Model to identify which user is following whom"""

    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name=_("user"),
    )
    followed_user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="followed_by",
        verbose_name=_("follower"),
    )

    def __str__(self):
        return f"{self.user} <{self.followed_user}>"

    class Meta:
        unique_together = ["user", "followed_user"]

litrevu/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

UserModel = get_user_model()


class RegisterForm(UserCreationForm):
    """Form to register User"""

    class Meta:
        model = UserModel
        fields = ["username", "password1", "password2"]


class AboForm(forms.Form):
    """form for the abo page, to follow and unfollow users"""

    search = forms.CharField(max_length=50, label=False)

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_search(self):
        search = self.cleaned_data["search"]

        # impossible to follow yourself:
        if self.user and self.user.username == search:
            raise forms.ValidationError("You can not follow yourself!")

        # impossible to follow an admin/superuser:
        if UserModel.objects.filter(username=search, is_superuser=True).exists():
            raise forms.ValidationError("Please choose an other name to follow!")

        return search

litrevu/accounts/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, CreateView, DeleteView

from .forms import RegisterForm, AboForm
from .models import UserFollow

UserModel = get_user_model()


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = "register.html"
    success_url = reverse_lazy("review:feeds_page")

    # TODO: after register not redirected to feeds_page
    def form_valid(self, form):
        user = form.save()

        if user:
            login(self.request, user)

        return super().form_valid(form)


class AboFollowView(LoginRequiredMixin, FormView):
    """View for the abo page. Follow a user and list the users who are following the user"""

    # TODO: you are following this user already

    model = UserFollow
    form_class = AboForm
    template_name = "abo_page.html"
    success_url = reverse_lazy("accounts:abo_page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["followed_users"] = self.request.user.following.all()
        context["followed_by_others"] = UserFollow.objects.filter(
            followed_user=self.request.user
        )

        return context

    def form_valid(self, form):
        if "follow" in form.data:
            user_to_follow = get_object_or_404(
                UserModel, username=form.cleaned_data["search"]
            )
            user_follows = UserFollow(
                user=self.request.user, followed_user=user_to_follow
            )
            user_follows.save()

        else:
            return reverse_lazy("accounts:abo_page")

        return super().form_valid(form)


class AboUnfollowView(LoginRequiredMixin, DeleteView):
    """View to unfollow a user."""

    # TODO: unfollow to do

    model = UserFollow
    fields = ["user"]
    template_name = "posts/delete_confirmation.html"
    success_url = reverse_lazy("accounts:abo_page")

    # def form_valid(self, form):
    #     if "unfollow" in form.data:
    #         print("unfollow", form.data)
    #         print("------", self.__dict__)
    # user_to_unfollow = get_object_or_404(UserModel, id=form.data.get("unfollow"))
    # UserFollows.objects.get(
    #     user=self.request.user, followed_user=user_to_unfollow
    # ).delete()

litrevu/accounts/templates/abo_page.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- abo page -->
<div class="container main">
  <div class="container justify-content-center">
      <div style="margin-bottom: 30px;">
        <form action="/abo/" method="post">
        {% csrf_token %}
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td class="user-input"> <button type="submit" class="btn btn-primary btn-sm" name="follow" value="{{ user.id }}" style="margin: 3px"> Follow </button> {{ form.as_p }} </td>
              </tr>
            </tbody>
          </table>
        </form>
      </div>

      {% if followed_users %}
      <div style="margin-bottom: 30px;">
        <form method="post">
          <h4> {{ request.user }} is following: </h4>
          {% for followed_user in followed_users %}
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td><a class="btn btn-warning btn-sm" href="{% url 'accounts:abo_unfollow' pk=followed_user.followed_user.pk %}" role="button" style="margin-top: 20px;"> Unfollow </a> {{ followed_user.followed_user.username }} </td>
              </tr>
            </tbody>
          </table>
          {% endfor %}
        </form>
      </div>
      {% endif %}

      {% if followed_by_others %}
      <div>
        <h4> You are being followed by: </h4>
        {% for user in followed_by_others %}
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td> {{ user.user.username }} </td>
              </tr>
            </tbody>
          </table>
        {% endfor %}
      </div>
      {% endif %}
  </div>
</div>
<!-- End of abo page -->
{% endblock %}

litrevu/accounts/templates/homepage.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card border-dark bg-light my-3" >
        <div class="card-body bg-transparent ">
          <h4> Register now ! </h4>
          <a class="btn btn-primary" href="{% url 'register' %}" role="button"> Sign up </a>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <div class="card border-dark bg-light my-3" >
        <div class="card-body bg-transparent ">
        {% crispy form %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

litrevu/accounts/templates/login_page.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Home page: register and login -->
<div class="container main">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card border-dark my-3" style="background-color: #e3f2fd;">
        <div class="card-body bg-transparent text-center">
          <h4> Register now ! </h4>
          <a class="btn btn-primary margin-btn" href="{% url 'accounts:register' %}" role="button"> Sign up </a>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card border-dark my-3" style="background-color: #e3f2fd;">
        <div class="card-body bg-transparent">
          <h4 class="card-subtitle text-center py-2"> Log in: </h4>
          <form method="post">
            {% csrf_token %}
              {{ form|crispy }}
              <div>
                <button type="submit" class="btn btn-primary margin-btn"> Log in </button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

litrevu/accounts/templates/register.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container main mt-4">
  <div class="card border-dark my-3 w-75" style="background-color: #e3f2fd;">
    <div class="card-body bg-transparent ">
      <h4 class="card-subtitle text-center py-2"> Register now: </h4>
        <form method="post">
          {% csrf_token %}
            {{ form|crispy }}
            <div style="display: flex; justify-content: space-between;">
              <button type="submit" class="btn btn-primary margin-btn"> Register </button>
              <a href="{% url 'accounts:login' %}" role="button" class="btn btn-secondary margin-btn"> Cancel </a>
            </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}